### ISSUE TITLE
Build issue in QT5.X

### ISSUE THREAD

**Issue by Linloir** [Linloir/GraphBuilder#3]
`QEnterEvent` & `globalPosition()` cause building issues in QT version below 6

**Comment by Linloir** [comment]
Changing `QEnterEvent` -> `QEvent` & changing `globalPosition()` -> `globalPos()` will fix the problem ;P

**Comment by wineee** [comment]
Maybe you need:
```cpp
#if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
    a->globalPos();
#else
    a->globalPosition();
#endif
```

**Comment by Linloir** [comment]
> Maybe you need:
> 
> ```c++
> #if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
>     a->globalPos();
> #else
>     a->globalPosition();
> #endif
> ```

nice suggestion, adopted XD
