### ISSUE TITLE
有一个小疑问

### ISSUE THREAD

**Issue by bakashigure** [Linloir/GraphBuilder#5]
您好~~ 能解答一个小问题吗
下面这段代码的功能是不是: 经过10ms触发`timeout`然后调用`Init`?
为啥在`mainwindow.cpp`的类构造函数里面会用`QTimer`来调用`Init`呀
```
QTimer *t = new QTimer(this);
connect(t, &QTimer::timeout, this, [=](){Init();});
t->setSingleShot(true);
t->start(10);
```
我试了一下把这段删掉直接调用`Init()`会导致UI布局错误，期待解答。

**Comment by Linloir** [comment]
我之前就是被这个问题折磨了一段时间，这个关系到Qt控件创建和大小调整的一个先后次序，默认是这样的：
`创建新的控件` -> `初始化器将控件大小初始化` -> `构造函数按照初始化出的大小初始化子控件` -> `新的控件被添加到布局` -> `布局管理对控件大小按照伸缩策略调整`
在上面这个过程中，由于子控件在父控件被布局管理接手之前就尝试获取了父控件的大小来计算一些大小或是坐标，会导致错误
所以通过一个极短的延迟等待父控件大小被布局管理正确设置后再使用`Init()`函数来创建子控件就可以正确获取父控件的大小了

**Comment by bakashigure** [comment]
大概理解了...谢谢解答
