### ISSUE TITLE
来我们这做编译器吧

### ISSUE THREAD

**Issue by Liaoshihua** [Linloir/GraphBuilder#8]
要不要来我们这做编译器？
https://github.com/lazyparser/weloveinterns

**Comment by Linloir** [comment]
最近一直在忙学校考试周的事情，实在不好意思没有及时回复
首先十分感激您的邀请，仔细了解了一下您的仓库，由于我本身起步比较晚，还有很多知识需要学习，感觉目前我的水平还不足以胜任其中的许多工作，所以十分遗憾我目前可能没办法加入你们。如果大三时还有机会，再与您联系，不甚感激。

**Comment by Liaoshihua** [comment]
不用介意，我们这的实习均为远程岗位，具体岗位与要求在https://github.com/lazyparser/weloveinterns 这个链接里面，实习可以随时开始也可以随时结束。等你有兴趣的时候按链接里的方式投递简历即可。

祝你学习进步，生活愉快
