### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by Echo-b** [Linloir/GraphBuilder#9]
您好，请问你的qt版本具体是？ 我这里版本可能比较低，编译时error 和 warning比较多。谢谢

**Comment by Linloir** [comment]
已经针对QT5.9.9进行了一些调整，可以尝试问题是否仍然存在
我的QT版本是Qt6.1 / Windows 11 以及Qt5.9.9 / Ubuntu20.04 LTS

**Comment by Echo-b** [comment]
> 已经针对QT5.9.9进行了一些调整，可以尝试问题是否仍然存在 我的QT版本是Qt6.1 / Windows 11 以及Qt5.9.9 / Ubuntu20.04 LTS

已解决，十分感谢
